id: P6CF86201
initial_creation_type: input
source_metadata:
  title: Yangchen Drubpe Dorje Series
  language: en
  description: 'A series of texts by the famous master Yangchen Drubpe Dorje (dbyangs
    can grub pa''i rdo rje, 1809–1887):'
  volume:
    9e09eb494865440e9c9383953d9de964:
      title: 'The Magical Wish-Fulfilling Tree: The Essence of Thönmi’s Masterpiece
        ''The Thirty Verses'''
      parent: Grammar
created_at: '2022-03-01T02:01:03.543471'
last_modified_at: '2022-03-01T02:01:03.543477'
